name: Build Kashif APK
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y zip unzip python3-pip openjdk-17-jdk
          pip install buildozer cython

      - name: Unzip project
        run: |
          if [ -f kashef-project.zip ]; then
            unzip -o kashef-project.zip
            ls -la
          else
            echo "zip not found"
            ls -la
          fi

      - name: Build APK
        run: |
          if [ -f buildozer.spec ]; then
            buildozer android debug
          else
            find . -name "buildozer.spec"
            cd $(find . -name "buildozer.spec" -exec dirname {} \; | head -n 1)
            buildozer android debug
          fi

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Kashif-APK
          path: |
            **/*.apk
            bin/*.apk
